variables:
    WORKON_HOME: .pipenv/venvs
    PIP_CACHE_DIR: .pipenv/pipcache

cache:
    key:
        files:
            - Pipfile.lock
    paths:
        - .pipenv

default:
    image: python:3.8-alpine
    before_script:
        - apk add musl-dev gcc
        - pip3 install pipenv
        - pipenv install

typecheck:
    stage: test
    script:
        - pipenv run mypy ctfkit

unittest:
    stage: test
    before_script:
        - apk add nodejs git gcc 
    script:
        - pipenv run python3 -m unittest discover tests -b

pylint:
    stage: test
    allow_failure: true
    script:
        - pipenv run python3 -m pylint
            --exit-zero
            --output-format=pylint_gitlab.GitlabCodeClimateReporter
            ctfkit > codeclimate.json
    artifacts:
        reports:
            codequality: codeclimate.json
        when: always