site_name: CTFKit
site_url: 'https://ctf-kit.fr'
repo_url: https://git.fakenews.sh/ctfkit/ctfkit
theme: material
markdown_extensions:
  - attr_list
  - mkdocs-click
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  - pdf-export:
      combined: true
      enabled_if_env: PDF